# Generated by Django 2.2 on 2020-10-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
