# Generated by Django 2.2 on 2020-10-03 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201003_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Level'),
        ),
    ]
