# Generated by Django 2.2 on 2020-10-03 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_current_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='current_pont_limit_for_day',
            new_name='current_point_limit_for_day',
        ),
    ]
