# Generated by Django 2.2 on 2020-10-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201004_0020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='points',
            options={'verbose_name_plural': 'Points'},
        ),
        migrations.AddField(
            model_name='review',
            name='points_earned',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shortstory',
            name='points_earned',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='points',
            unique_together=set(),
        ),
    ]
