# Generated by Django 2.2 on 2020-10-04 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20201004_0125'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
