# Generated by Django 2.2 on 2020-10-05 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_delete_useractivity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='points',
            options={'ordering': ('action', 'points'), 'verbose_name_plural': 'Points'},
        ),
        migrations.AlterUniqueTogether(
            name='points',
            unique_together={('action', 'level')},
        ),
    ]
